/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11/userguide/building_java_projects.html in the Gradle documentation.
 */

description = "A simple mathematical operations application."

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


plugins {
    java
    application
    id("checkstyle") // Apply the Checkstyle plugin
    id("pmd") // Apply the PMD plugin
}

pmd {
    toolVersion = "6.56.0" // Specify the PMD version
    // ruleSets = listOf("java-basic", "java-design") // Default rule sets
    ruleSetFiles = files("config/pmd/ruleset.xml") // Optional custom rules   
    isConsoleOutput = true // Print results to console
}


checkstyle {
    toolVersion = "10.12.0" // Specify the Checkstyle version
    configFile = file("config/checkstyle/checkstyle.xml") // Path to Checkstyle configuration file
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-math3:3.6.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    pmd("net.sourceforge.pmd:pmd-dist:7.8.0")
}

application {
    mainClass.set("org.example.App")
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "org.example.App"
        )
    }
}

version = "1.0.0"
