name: Release Automation

on:
  push:
    tags:
      - 'v*' # Matches tags like v1.0, v2.0.1, etc.

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Generate Changelog
      id: changelog
      run: |
        git fetch --tags
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "HEAD")
        echo "Previous Tag: $PREVIOUS_TAG"
        CHANGELOG=$(git log --oneline $PREVIOUS_TAG..HEAD)
        echo "Changelog: $CHANGELOG"
        echo "::set-output name=log::$CHANGELOG"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.log }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Build Artifacts
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/libs/app-1.0.0.jar
        asset_name: app-1.0.0.jar
        asset_content_type: application/java-archive
